version: '2'
services:
    nav_app-app:
        image: nav_app
        external_links:
            - nav_app-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/nav_app?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nav_app-mysql:
        extends:
            file: mysql.yml
            service: nav_app-mysql
