version: '2'
services:
    nav_app-mysql:
        container_name: nav_app-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/nav_app/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=nav_app
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
